update: uninstall unused

diff --git a/helperscripts/update b/helperscripts/update
--- a/helperscripts/update
+++ b/helperscripts/update
@@ -77,6 +77,7 @@ apt-get clean || die "Clean failed"
 if command -v flatpak >/dev/null 2>&1; then
 	info "Updating flatpaks"
 	flatpak update || die "flatpak update failed"
+	flatpak uninstall --unused || die "flatpak uninstall --unused failed"
 fi
 
 if command -v rpi-eeprom-update >/dev/null 2>&1; then
