Add flatpak update

diff --git a/helperscripts/update b/helperscripts/update
--- a/helperscripts/update
+++ b/helperscripts/update
@@ -111,4 +111,9 @@ apt $dl_flags --show-upgraded --verbose-versions "$upgrade_mode" ||\
 info "Cleaning"
 apt-get clean || die "Clean failed"
 
+if command -v my-flatpak-update >/dev/null 2>&1; then
+	info "Updating flatpaks"
+	flatpak update --noninteractive || die "my-flatpak-update failed"
+fi
+
 exit 0
