Add apt tools
Signed-off-by: Michael Buesch <m@bues.ch>

diff --git a/helperscripts/update b/helperscripts/update
--- a/helperscripts/update
+++ b/helperscripts/update
@@ -1,4 +1,61 @@
 #!/bin/sh
-aptitude update &&\
-aptitude safe-upgrade &&\
-aptitude clean
+
+listfile=/tmp/update-files.list
+aria2c_jobs=16
+
+die()
+{
+	echo "$*" >&2
+	exit 1
+}
+
+info()
+{
+	echo "--- $*"
+}
+
+full=0
+
+while [ $# -ge 1 ]; do
+	case "$1" in
+	--full)
+		full=1
+		;;
+	*)
+		die "Unknown parameter: $1"
+		;;
+	esac
+	shift
+done
+
+info "Updating package list"
+aptitude update || die "Update failed"
+
+[ $full -eq 0 ] && {
+	apt_param="upgrade"
+	aptitude_param="safe-upgrade"
+} || {
+	apt_param="dist-upgrade"
+	aptitude_param="full-upgrade"
+}
+
+info "Generating package list for '$aptitude_param'"
+apt-uri-list $apt_param | apturi2metalink > "$listfile" ||\
+	die "Failed to generate file list"
+
+info "Downloading packages"
+while true; do
+	aria2c -j "$aria2c_jobs" -s "$aria2c_jobs" -x "$aria2c_jobs" -t 120 \
+		-k 1048576 --retry-wait=1 -d /var/cache/apt/archives/ \
+		"$listfile" && break
+	sleep 10
+done
+rm "$listfile"
+
+info "Performing '$aptitude_param'"
+aptitude $aptitude_param || die "Upgrade failed"
+
+info "Cleaning"
+aptitude clean || die "Clean failed"
+
+exit 0
