update: Add snap

diff --git a/helperscripts/update b/helperscripts/update
--- a/helperscripts/update
+++ b/helperscripts/update
@@ -80,6 +80,11 @@ if command -v flatpak >/dev/null 2>&1; then
 	flatpak uninstall --unused || die "flatpak uninstall --unused failed"
 fi
 
+if command -v snap >/dev/null 2>&1; then
+	info "Updating snaps"
+	snap refresh || die "snap refresh failed"
+fi
+
 if command -v rpi-eeprom-update >/dev/null 2>&1; then
 	info "Updating Raspberry Pi EEPROMs"
 	rpi-eeprom-update -a || die "Raspberry Pi EEPROM update failed"
